repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^tests/
        language_version: python3.
        args: # arguments to configure black
          - --line-length=88

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
        files: \.py$
        language_version: python3.

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^tests/
        language_version: python3.
        args:
          - --max-line-length=119
          - --max-complexity=25
          - --ignore=E203,W503

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        args:
          - --ignore-missing-imports
          - --install-types # See mirrors-mypy README.md
          - --non-interactive
          - --no-strict-optional

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

